spring:
  application:
    name: monitoringDemo

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,loggers
  metrics:
    tags:
      application: ${spring.application.name}
