---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoringDemo-service-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: monitoringDemo
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"